version: "3.9"
services:
  bioc:
    container_name: bioc-3.16
    #image: "bioconductor/bioconductor_docker:devel"
    build: ./
    ports:
      - "8787:8787"
    environment:
      - PASSWORD=bioc
    volumes:
      - ./lib/:/usr/local/lib/R/host-site-library
      - ./data/:/usr/local/host-site-data